import type { PollutionRecord } from '../types/pollution';

export const SUPPLEMENTAL_RECORDS: PollutionRecord[] = [
  {
    id: 'supp-aqi-mysuru-2026-03-30',
    category: 'aqi',
    pollutionType: 'air',
    name: 'Mysuru Supplemental AQI Station',
    district: 'Mysuru',
    city: 'Mysuru',
    latitude: 12.2958,
    longitude: 76.6394,
    date: '2026-03-30',
    source: 'Supplemental Karnataka AQI',
    measurements: {
      usAqi: 76,
      pm25: 31,
      pm10: 52,
      no2: 18,
      ozone: 41,
    },
  },
  {
    id: 'supp-aqi-hubballi-2026-03-30',
    category: 'aqi',
    pollutionType: 'air',
    name: 'Hubballi Supplemental AQI Station',
    district: 'Dharwad',
    city: 'Hubballi',
    latitude: 15.3647,
    longitude: 75.124,
    date: '2026-03-30',
    source: 'Supplemental Karnataka AQI',
    measurements: {
      usAqi: 89,
      pm25: 38,
      pm10: 61,
      no2: 23,
      ozone: 47,
    },
  },
  {
    id: 'supp-aqi-mangaluru-2026-03-30',
    category: 'aqi',
    pollutionType: 'air',
    name: 'Mangaluru Supplemental AQI Station',
    district: 'Dakshina Kannada',
    city: 'Mangaluru',
    latitude: 12.9141,
    longitude: 74.856,
    date: '2026-03-30',
    source: 'Supplemental Karnataka AQI',
    measurements: {
      usAqi: 64,
      pm25: 24,
      pm10: 44,
      no2: 16,
      ozone: 36,
    },
  },
  {
    id: 'supp-lake-sankey-2026-03-20',
    category: 'lake-quality',
    pollutionType: 'water',
    name: 'SANKEY LAKE',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    latitude: 12.9906,
    longitude: 77.5725,
    date: '2026-03-20',
    source: 'Supplemental Lake Quality Survey',
    measurements: {
      dissolvedOxygen: 5.4,
      pH: 7.3,
      bod: 3.2,
      nitrateN: 1.2,
      totalDissolvedSolids: 350,
    },
  },
  {
    id: 'supp-lake-lalbagh-2026-03-20',
    category: 'lake-quality',
    pollutionType: 'water',
    name: 'LALBAGH LAKE',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    latitude: 12.9507,
    longitude: 77.5848,
    date: '2026-03-20',
    source: 'Supplemental Lake Quality Survey',
    measurements: {
      dissolvedOxygen: 4.7,
      pH: 7.1,
      bod: 4.1,
      nitrateN: 1.6,
      totalDissolvedSolids: 410,
    },
  },
  {
    id: 'supp-lake-hoysala-2026-03-20',
    category: 'lake-quality',
    pollutionType: 'water',
    name: 'HOYSALA LAKE',
    district: 'Shivamogga',
    city: 'Shivamogga',
    latitude: 13.926,
    longitude: 75.5772,
    date: '2026-03-20',
    source: 'Supplemental Lake Quality Survey',
    measurements: {
      dissolvedOxygen: 6.2,
      pH: 7.5,
      bod: 2.3,
      nitrateN: 0.9,
      totalDissolvedSolids: 290,
    },
  },
];
